### ISSUE TITLE
SSL сертификат просрочет

### ISSUE THREAD

**Issue by zerg4000** [yiiframework-ua/yiiframework.com.ua#16]
SSL сертификат просрочет.
<img width="1319" alt="Screenshot 2020-09-27 at 12 17 56" src="https://user-images.githubusercontent.com/24324641/94361236-84b0dd80-00bb-11eb-8c76-3d247d91f5d7.png">

**Comment by Borales** [comment]
@zerg4000 спасибо, исправлено!
