### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by igogo5yo** [yiiframework-ua/yiiframework.com.ua#3]
Привет!
Нашел багу на сайте:
Зарегестрировался используя github аккаунт.
Перешел в профиль - https://yiiframework.com.ua/ru/profile/
И нажал "Выйти", после чего я остался на ПУСТОЙ странице профиля - http://joxi.ru/QeAODdOueL8wro

**Comment by Borales** [comment]
@igogo5yo спасибо, будет исправлено

**Comment by Borales** [comment]
Исправлено
