### ISSUE TITLE
Пожелание

### ISSUE THREAD

**Issue by jofreyswb** [yiiframework-ua/yiiframework.com.ua#8]
Сделайте пожалуйста кнопочку вверх. Когда читаешь очень неудобно потом скролить  обратно. Заранее огромное спасибо. 
И еще если вы видели ето собщенние отпишите пожалуйста на почту
начал изучать фреймвор есть несколько вопросов, если вам не трудно ответить.

**Comment by Borales** [comment]
@jofreyswb с небольшой задержкой, но всё же сделано )

**Comment by jofreyswb** [comment]
спасибо
